services:
  pygeoapi:
    image: geopython/pygeoapi:latest
    container_name: pygeoapi
    ports:
      - 5000:80
    volumes:
      - ./pygeoapi.config.yml:/pygeoapi/local.config.yml
      - ./__init__.py:/pygeoapi/pygeoapi/api/__init__.py
      - ./newapi.py:/pygeoapi/pygeoapi/api/newapi.py
      - ./flask_app.py:/pygeoapi/flask_app.py
