services:
  pygeoapi:
    image: geopython/pygeoapi:latest
    container_name: pygeoapi
    ports:
      - 5000:80
    volumes:
      - ./pygeoapi.config.yml:/pygeoapi/local.config.yml
      - ./__init__.py:/pygeoapi/pygeoapi/api/__init__.py
      - ./itemstype.py:/pygeoapi/pygeoapi/api/itemstype.py
      # - ./changeset.html:/pygeoapi/templates/collections/changeset.html
      - ./flask_app.py:/pygeoapi/flask_app.py
    environment:
      - PYGEOAPI_CONFIG=/pygeoapi/local.config.yml
      - PYGEOAPI_OPENAPI=/pygeoapi/local.openapi.yml
